import uuid
from typing import Optional, Dict, Any, Sequence
from pydantic import EmailStr, BaseModel as PydanticBaseModel

from sqlalchemy import select, update as sql_update, delete as sql_delete
from sqlalchemy.ext.asyncio import AsyncSession

from enableai_hub.auth.models import User # SQLAlchemy model
# Password hashing utilities will be added later
# from passlib.context import CryptContext # Example for password hashing

# pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto") # Example

# Pydantic model for creating a user (input validation)
class UserCreate(PydanticBaseModel):
    email: EmailStr
    password: str # Plain password from user input, will be hashed
    full_name: Optional[str] = None
    is_active: bool = True # Default value
    is_superuser: bool = False # Default value

# Pydantic model for updating a user (input validation)
class UserUpdate(PydanticBaseModel):
    email: Optional[EmailStr] = None
    full_name: Optional[str] = None
    is_active: Optional[bool] = None
    is_superuser: Optional[bool] = None
    # password: Optional[str] = None # Password updates handled separately usually


async def get_user(db_session: AsyncSession, user_id: uuid.UUID) -> Optional[User]:
    """Retrieve a user by their ID from the database."""
    result = await db_session.execute(select(User).filter(User.id == user_id))
    return result.scalars().first()

async def get_user_by_email(db_session: AsyncSession, email: EmailStr) -> Optional[User]:
    """Retrieve a user by their email address from the database."""
    result = await db_session.execute(select(User).filter(User.email == email))
    return result.scalars().first()

async def create_user(db_session: AsyncSession, user_in: UserCreate) -> User:
    """
    Create a new user in the database.
    Password hashing will be implemented properly later.
    """
    existing_user = await get_user_by_email(db_session, user_in.email)
    if existing_user:
        raise ValueError(f"User with email {user_in.email} already exists.")

    # For now, storing password as plain text or placeholder.
    # Replace with actual hashing: hashed_password = pwd_context.hash(user_in.password)
    hashed_password_placeholder = f"hashed_{user_in.password}_placeholder"

    db_user = User(
        email=user_in.email,
        hashed_password=hashed_password_placeholder, # Store placeholder
        full_name=user_in.full_name,
        is_active=user_in.is_active,
        is_superuser=user_in.is_superuser
        # id is generated by default by the model
    )
    db_session.add(db_user)
    await db_session.flush() # Use flush to get the ID if needed before commit (if not using default from client)
    # await db_session.commit() # Commit is handled by the get_db_session dependency usually
    await db_session.refresh(db_user) # Refresh to get DB-generated values like created_at
    return db_user

async def update_user(db_session: AsyncSession, user_id: uuid.UUID, user_in: UserUpdate) -> Optional[User]:
    """Update an existing user in the database."""
    db_user = await get_user(db_session, user_id)
    if not db_user:
        return None

    update_data = user_in.model_dump(exclude_unset=True) # Pydantic v2
    # update_data = user_in.dict(exclude_unset=True) # Pydantic v1

    for field, value in update_data.items():
        setattr(db_user, field, value)

    db_session.add(db_user) # Add the updated object to the session
    # await db_session.commit() # Handled by dependency
    await db_session.refresh(db_user)
    return db_user

async def delete_user(db_session: AsyncSession, user_id: uuid.UUID) -> bool:
    """
    Delete a user from the database.
    Returns True if user was deleted, False otherwise.
    """
    db_user = await get_user(db_session, user_id)
    if not db_user:
        return False

    await db_session.delete(db_user)
    # await db_session.commit() # Handled by dependency
    return True

async def get_users(
    db_session: AsyncSession, skip: int = 0, limit: int = 100
) -> Sequence[User]:
    """
    Retrieve a list of users with pagination.
    """
    result = await db_session.execute(
        select(User).offset(skip).limit(limit)
    )
    return result.scalars().all()

# Notes:
# - The commit calls are commented out because the `get_db_session` dependency
#   is expected to handle the session commit/rollback.
# - Error handling (e.g., for database integrity errors on create_user) can be more specific.
# - Password management (hashing, updates) needs a dedicated effort.
