import uuid
from typing import Optional, List, Dict, Any, Sequence
from pydantic import BaseModel as PydanticBaseModel, Field, HttpUrl

from sqlalchemy import select, delete as sql_delete
from sqlalchemy.ext.asyncio import AsyncSession

from arcade_platform.tools.models import ToolDefinition # SQLAlchemy model
# Assuming ToolParameterDefinition is part of the JSON schema in ToolDefinition model for now
# If ToolParameterDefinition were a separate table, it would be handled differently.

# Pydantic model for creating a tool (input validation)
class ToolDefinitionCreate(PydanticBaseModel):
    name: str
    description: Optional[str] = None
    parameters_schema: Optional[Dict[str, Any]] = Field(default_factory=dict) # JSON schema for params
    auth_required: bool = False
    auth_scopes: List[str] = Field(default_factory=list)
    execution_timeout_seconds: int = Field(default=30, gt=0)
    version: str = "1.0.0"
    invocation_details: Optional[Dict[str, Any]] = None
    is_active: bool = True

# Pydantic model for updating a tool (input validation)
class ToolDefinitionUpdate(PydanticBaseModel):
    name: Optional[str] = None
    description: Optional[str] = None
    parameters_schema: Optional[Dict[str, Any]] = None
    auth_required: Optional[bool] = None
    auth_scopes: Optional[List[str]] = None
    execution_timeout_seconds: Optional[int] = Field(default=None, gt=0)
    version: Optional[str] = None
    invocation_details: Optional[Dict[str, Any]] = None
    is_active: Optional[bool] = None


class ToolRegistry:
    async def register_tool(self, db_session: AsyncSession, tool_in: ToolDefinitionCreate) -> ToolDefinition:
        """Registers a new tool or updates an existing one if identified by name+version (not implemented yet)."""
        # Basic check, more complex logic for update-or-create can be added
        # existing_tool = await self.get_tool_by_name_and_version(db_session, tool_in.name, tool_in.version)
        # if existing_tool:
        #     raise ValueError(f"Tool '{tool_in.name}' version '{tool_in.version}' already exists.")

        db_tool = ToolDefinition(
            # id is generated by default by the model
            name=tool_in.name,
            description=tool_in.description,
            parameters_schema=tool_in.parameters_schema,
            auth_required=tool_in.auth_required,
            auth_scopes=tool_in.auth_scopes,
            execution_timeout_seconds=tool_in.execution_timeout_seconds,
            version=tool_in.version,
            invocation_details=tool_in.invocation_details,
            is_active=tool_in.is_active
        )
        db_session.add(db_tool)
        await db_session.flush() # To get default values like ID if needed before returning
        # await db_session.commit() # Handled by dependency
        await db_session.refresh(db_tool) # To get DB-generated values like created_at
        return db_tool

    async def get_tool_definition(self, db_session: AsyncSession, tool_id: uuid.UUID) -> Optional[ToolDefinition]:
        """Retrieves a tool definition by its ID."""
        result = await db_session.execute(
            select(ToolDefinition).filter(ToolDefinition.id == tool_id)
        )
        return result.scalars().first()

    async def get_tool_definition_by_name_version(
        self, db_session: AsyncSession, name: str, version: str
    ) -> Optional[ToolDefinition]:
        """Retrieves a tool definition by its name and version."""
        result = await db_session.execute(
            select(ToolDefinition).filter_by(name=name, version=version)
        )
        return result.scalars().first()

    async def list_tools(
        self,
        db_session: AsyncSession,
        skip: int = 0,
        limit: int = 100,
        is_active: Optional[bool] = None # Filter by active status
        # user_id: Optional[uuid.UUID] = None # For future user-specific authorization
    ) -> Sequence[ToolDefinition]:
        """Lists available tools with pagination and optional active filter."""
        query = select(ToolDefinition)
        if is_active is not None:
            query = query.filter(ToolDefinition.is_active == is_active)

        query = query.offset(skip).limit(limit)
        result = await db_session.execute(query)
        return result.scalars().all()

    async def update_tool_definition(
        self, db_session: AsyncSession, tool_id: uuid.UUID, tool_in: ToolDefinitionUpdate
    ) -> Optional[ToolDefinition]:
        """Updates an existing tool definition."""
        db_tool = await self.get_tool_definition(db_session, tool_id)
        if not db_tool:
            return None

        update_data = tool_in.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            setattr(db_tool, field, value)

        db_session.add(db_tool)
        # await db_session.commit() # Handled by dependency
        await db_session.refresh(db_tool)
        return db_tool

    async def unregister_tool(self, db_session: AsyncSession, tool_id: uuid.UUID) -> bool:
        """Removes a tool from the registry by its ID."""
        db_tool = await self.get_tool_definition(db_session, tool_id)
        if not db_tool:
            return False

        await db_session.delete(db_tool)
        # await db_session.commit() # Handled by dependency
        return True

# Placeholder for methods related to user authorization for tools
# async def authorize_tool_for_user(self, user_id: uuid.UUID, tool_id: str, authorization_details: Dict[str, Any]):
#     pass
# async def get_user_authorized_tools(self, user_id: uuid.UUID) -> List[ToolDefinition]:
#     pass

# The previous Pydantic models for ToolDefinition and ToolParameterDefinition in this file are removed
# as the SQLAlchemy model is now primary, and ToolDefinitionCreate/Update are used for input.
